import { build } from "esbuild";
// Vercel needs a standalone handler for /api/mcp; bundle the mcp/ folder.
await build({
  entryPoints: ["mcp/entry.ts"],
  outfile: "api/mcp.js",
  bundle: true,
  platform: "node",
  format: "esm",
  packages: "external",
  banner: {
    js: "// Generated by scripts/security/build-mcp.mjs. Do not edit.",
  },
});
