-- Settings fix, part 4 of 5: remove the old one-copy-for-everyone rules.
-- Safe now that the app (9848a3a) and the pipeline's thumbtack-notify (5fc6fe7)
-- both save against the per-company rules added in 20261008045850.
--   app_settings      → only (tenant_id, key) is unique; "key" alone no longer is
--   pricing_defaults  → id is a normal auto number; one row per company via
--                       pricing_defaults_tenant_key (Progressive keeps id 1)
begin;

alter table public.app_settings drop constraint app_settings_key_key;

alter table public.pricing_defaults drop constraint pricing_defaults_id_check;
alter table public.pricing_defaults alter column id drop default;
alter table public.pricing_defaults
  alter column id add generated by default as identity (start with 2);

commit;
