// Generated by scripts/security/build-booking-api.mjs. Do not edit.

// server/booking/handler.ts
import { randomUUID } from "node:crypto";
import { createClient as createClient2 } from "@supabase/supabase-js";
import { Resend } from "resend";

// client/src/data/movingRates.ts
var ASSEMBLY_SKUS = Object.freeze([
  { id: "dining_chair", name: "Dining chair", price: 35 },
  { id: "office_chair", name: "Office chair", price: 45 },
  { id: "nightstand_small_table", name: "Nightstand / small table", price: 65 },
  { id: "desk", name: "Desk", price: 125 },
  { id: "tv_stand", name: "TV stand", price: 125 },
  { id: "dresser", name: "Dresser", price: 150 },
  { id: "bed_frame", name: "Bed frame", price: 175 },
  { id: "bunk_bed", name: "Bunk bed", price: 350 },
  { id: "shelving_storage", name: "Shelving / storage unit", price: 225 },
  { id: "ikea_small", name: "IKEA \u2014 small piece", price: 149 },
  { id: "ikea_large", name: "IKEA \u2014 large piece", price: 399 },
  { id: "five_item_bundle", name: "5-item bundle", price: 199 },
  { id: "play_equipment", name: "Play equipment (small kit)", price: 195 }
]);
var HOURS_TABLE = Object.freeze({
  few_items: { 2: { low: 2, high: 2 }, 3: { low: 2, high: 2 }, 4: null },
  studio_1br: { 2: { low: 3, high: 4 }, 3: { low: 2, high: 3 }, 4: null },
  "2br": {
    2: { low: 5, high: 6 },
    3: { low: 4, high: 5 },
    4: { low: 3, high: 4 }
  },
  "3br": {
    2: { low: 6, high: 8 },
    3: { low: 5, high: 6 },
    4: { low: 4, high: 5 }
  },
  "4br": {
    2: { low: 8, high: 10 },
    3: { low: 6, high: 8 },
    4: { low: 5, high: 7 }
  },
  "5br_plus": {
    2: { low: 10, high: 12 },
    3: { low: 8, high: 10 },
    4: { low: 7, high: 9 }
  }
});
var MOVING_RATES = Object.freeze({
  pricingVersion: "v19 2026-09-06",
  /** 2 movers + 26-ft liftgate truck, per hour. */
  hourly: { weekday: 109, weekend: 124 },
  /** Each mover beyond the second, per hour (same on weekends). */
  extraMoverPerHour: 50,
  /** Baked into every truck-job total. Never itemized to the customer. */
  tripFee: 85,
  /** Hourly jobs bill at least this many hours. */
  minimumHours: { default: 2, fourMovers: 4 },
  /** Any single-crew estimate above this needs dispatch review. */
  escalateAboveHours: 8,
  packages: {
    small_move: {
      key: "small_move",
      name: "Small Move \u2014 up to 8 items, no full rooms",
      price: { weekday: 303, weekend: 333 },
      includedHours: 2,
      crewShown: 2
    },
    studio_1br: {
      key: "studio_1br",
      name: "Apartment Move \u2014 Studio / 1BR",
      price: { weekday: 525, weekend: 595 },
      includedHours: 4,
      crewShown: 2
    },
    "2br": {
      key: "2br",
      name: "Apartment Move \u2014 2BR",
      price: { weekday: 750, weekend: 850 },
      includedHours: 6,
      crewShown: 3
    },
    small_house: {
      key: "small_house",
      name: "Home Move \u2014 Small House (up to 3BR, single level or one flight)",
      price: { weekday: 750, weekend: 850 },
      includedHours: 6,
      crewShown: 3
    }
  },
  /** Package overage past the included hours, billed in quarter hours. */
  packageOverage: { weekday: 109, weekend: 124 },
  /**
   * Stairs fees. Abe (Sep 18, 2026): "I don't charge for stairs" — the app charges $0 for stairs on
   * every option; stairs still add TIME on hourly jobs (`hoursPerFlight`). The v19 pipeline prompt
   * still tells customers "+$75 per additional flight" / "+$75 per location for a piano" — those
   * numbers are kept here (disabled) until David's prompt is reconciled.
   */
  chargeStairs: false,
  /** Packages (only when `chargeStairs`): first flight per address included, then this per extra flight per address. */
  extraFlightOfStairs: 75,
  /** Small Move qualifies up to this many items. */
  smallMoveMaxItems: 8,
  /** 2 movers, no truck, no trip fee. Weekend labor-only is $124/hr (Abe, Sep 9). */
  laborOnly: { weekday: 109, weekend: 124, minimumHours: 2 },
  /** Single large item (or item + its set), ≤ 15 miles between addresses. */
  vanFlat: { price: 199, maxMiles: 15 },
  /** One person + cargo van, single small item. No trip fee. */
  cargoVanSmallItem: 120,
  piano: {
    upright: 299,
    large_upright: 349,
    baby_grand: 399,
    grand: 499,
    /** Per location with stairs / difficult access — only when `chargeStairs`. */
    stairsPerLocation: 75
  },
  tvMount: { upTo65: 125, over65: 149 },
  packing: {
    /** Per 2 packers, per hour (labor-only rate). */
    ratePer2Packers: { weekday: 109, weekend: 124 },
    /** Abe (Sep 18): packer hours are entered directly (no box count) and materials are one flat amount per job. */
    defaultMaterialsFlat: 0
  },
  /** Wooden playset / swing set disassemble + reassemble. */
  playStructureFlat: 499,
  /** Address-to-address miles beyond the metro. The ONLY travel line ever itemized. */
  extendedTravel: {
    freeUpToMiles: 50,
    tiers: [
      { maxMiles: 75, price: 150, label: "51\u201375 mi" },
      { maxMiles: 100, price: 300, label: "76\u2013100 mi" }
    ]
  },
  /** Beyond this the job needs dispatch approval. */
  serviceAreaMiles: 50,
  /** Hours added per flight of stairs per address on hourly jobs (a 2nd story = one flight). */
  hoursPerFlight: { low: 0.5, high: 0.75 },
  /** `pricing_guards` — never quote below. Floors only ever raise a price. */
  floors: {
    hourly: { weekday: 109, weekend: 124 },
    extraMover: 50,
    tripFee: 85,
    smallMove: 303,
    studio: 525,
    twoBrOrSmallHouse: 750,
    laborOnlyMinimum: { weekday: 218, weekend: 248 },
    vanFlat: 199,
    cargoVan: 120,
    assembly: 125,
    tvMount: 125
  }
});
var PHOENIX_TZ = "America/Phoenix";
function daysInMonth(year, month) {
  return new Date(Date.UTC(year, month, 0)).getUTCDate();
}
function weekdayOf({ year, month, day }) {
  return new Date(Date.UTC(year, month - 1, day)).getUTCDay();
}
function toPhoenixDate(value) {
  if (typeof value === "string") {
    const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(value.trim());
    if (match) {
      const year = Number(match[1]);
      const month = Number(match[2]);
      const day = Number(match[3]);
      if (month < 1 || month > 12 || day < 1 || day > daysInMonth(year, month))
        return null;
      return { year, month, day };
    }
  }
  const date = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(date.getTime())) return null;
  const parts = new Intl.DateTimeFormat("en-US", {
    timeZone: PHOENIX_TZ,
    year: "numeric",
    month: "2-digit",
    day: "2-digit"
  }).formatToParts(date);
  const pick = (type) => Number(parts.find((part) => part.type === type)?.value);
  return { year: pick("year"), month: pick("month"), day: pick("day") };
}
function dayTypeOf(value) {
  const date = toPhoenixDate(value);
  if (!date) return "weekday";
  const weekday = weekdayOf(date);
  if (weekday === 0 || weekday === 5 || weekday === 6) return "weekend";
  const last = daysInMonth(date.year, date.month);
  if (date.day <= 2 || date.day >= last - 1) return "weekend";
  return "weekday";
}

// shared/bookingCatalog.ts
var BOOKING_DEPOSIT = 50;
var BOOKING_REFUND_HOURS = 24;
var BOOKING_DAYS_AHEAD = 45;
var R = MOVING_RATES;
var P = R.packages;
var overage = `then $${R.packageOverage.weekday}/hr ($${R.packageOverage.weekend} weekends), billed in quarter hours`;
var stairsLine = `First flight of stairs at each address included; $${R.extraFlightOfStairs} for each extra flight.`;
function junk(id, name, price, description) {
  return {
    id,
    group: "junk",
    subgroup: "Junk Removal",
    name,
    description,
    pricing: { kind: "flat", weekday: price, weekend: price },
    serviceType: "junk_removal",
    vehicleClass: "van",
    presetBoxTruck: false,
    fullDay: false,
    twoAddresses: false,
    stairs: "none",
    requiredCrew: 1
  };
}
function piano(id, name) {
  const price = R.piano[id];
  return {
    id: `piano_${id}`,
    group: "moving",
    subgroup: "Piano Moving",
    name,
    description: `Local piano move with a 26-ft liftgate truck, padded and strapped. $${R.piano.stairsPerLocation} per location with stairs or difficult access.`,
    pricing: { kind: "flat", weekday: price, weekend: price },
    serviceType: "moving",
    movingKind: "piano",
    vehicleClass: "box_truck",
    presetBoxTruck: true,
    fullDay: false,
    twoAddresses: true,
    stairs: "per_location",
    requiredCrew: 2
  };
}
var BOOKING_SERVICES = [
  {
    id: "small_move",
    group: "moving",
    subgroup: "Local Moving",
    name: "Small Move \u2014 up to 8 items (no full rooms)",
    description: `2 movers + 26-ft liftgate truck. ${P.small_move.includedHours} hours on site included, ${overage}. ${stairsLine}`,
    pricing: { kind: "flat", ...P.small_move.price },
    includedHours: P.small_move.includedHours,
    serviceType: "moving",
    movingKind: "small_move",
    vehicleClass: "box_truck",
    presetBoxTruck: true,
    fullDay: false,
    twoAddresses: true,
    stairs: "extra_flight",
    requiredCrew: 2
  },
  {
    id: "studio_1br",
    group: "moving",
    subgroup: "Local Moving",
    name: "Apartment Move \u2014 Studio / 1 Bedroom",
    description: `2 movers + 26-ft liftgate truck. ${P.studio_1br.includedHours} hours on site included, ${overage}. ${stairsLine}`,
    pricing: { kind: "flat", ...P.studio_1br.price },
    includedHours: P.studio_1br.includedHours,
    serviceType: "moving",
    movingKind: "studio_1br",
    vehicleClass: "box_truck",
    presetBoxTruck: true,
    fullDay: false,
    twoAddresses: true,
    stairs: "extra_flight",
    requiredCrew: 2
  },
  {
    id: "two_br",
    group: "moving",
    subgroup: "Local Moving",
    name: "Apartment Move \u2014 2 Bedroom",
    description: `3 movers + 26-ft liftgate truck. ${P["2br"].includedHours} hours on site included, ${overage}. ${stairsLine}`,
    pricing: { kind: "flat", ...P["2br"].price },
    includedHours: P["2br"].includedHours,
    serviceType: "moving",
    movingKind: "two_br",
    vehicleClass: "box_truck",
    presetBoxTruck: true,
    fullDay: true,
    twoAddresses: true,
    stairs: "extra_flight",
    requiredCrew: 3
  },
  {
    id: "small_house",
    group: "moving",
    subgroup: "Local Moving",
    name: "Home Move \u2014 Small House (up to 3 bedrooms)",
    description: `3 movers + 26-ft liftgate truck, single level or one flight. ${P.small_house.includedHours} hours on site included, ${overage}. ${stairsLine}`,
    pricing: { kind: "flat", ...P.small_house.price },
    includedHours: P.small_house.includedHours,
    serviceType: "moving",
    movingKind: "small_house",
    vehicleClass: "box_truck",
    presetBoxTruck: true,
    fullDay: true,
    twoAddresses: true,
    stairs: "extra_flight",
    requiredCrew: 3
  },
  {
    id: "hourly_2",
    group: "moving",
    subgroup: "Local Moving",
    name: "Hourly Move \u2014 2 Movers + 26-ft Truck",
    description: `Billed for actual time in quarter hours, ${R.minimumHours.default}-hour minimum. Travel included. Stairs add time, not fees.`,
    pricing: { kind: "hourly", ...R.hourly, minimumHours: R.minimumHours.default },
    serviceType: "moving",
    movingKind: "hourly_2",
    vehicleClass: "box_truck",
    presetBoxTruck: true,
    fullDay: false,
    twoAddresses: true,
    stairs: "time",
    requiredCrew: 2
  },
  {
    id: "labor_only",
    group: "moving",
    subgroup: "Labor Only",
    name: "Moving Labor \u2014 2 Movers, no truck",
    description: `Loading or unloading your truck, POD or storage unit. Billed for actual time, ${R.laborOnly.minimumHours}-hour minimum. Paid in full before the job.`,
    pricing: { kind: "hourly", weekday: R.laborOnly.weekday, weekend: R.laborOnly.weekend, minimumHours: R.laborOnly.minimumHours },
    serviceType: "moving",
    movingKind: "labor_only",
    vehicleClass: "box_truck",
    presetBoxTruck: false,
    fullDay: false,
    twoAddresses: false,
    stairs: "time",
    requiredCrew: 2
  },
  piano("upright", "Piano \u2014 Upright"),
  piano("large_upright", 'Piano \u2014 Large Upright (48"+)'),
  piano("baby_grand", "Piano \u2014 Baby Grand"),
  piano("grand", "Piano \u2014 Grand"),
  {
    id: "van_flat",
    group: "delivery",
    subgroup: "Cargo Van Delivery",
    name: "Cargo Van \u2014 Single Large Item",
    description: `One large item or a matching set (couch, dresser, appliance), up to ${R.vanFlat.maxMiles} miles between addresses.`,
    pricing: { kind: "flat", weekday: R.vanFlat.price, weekend: R.vanFlat.price },
    serviceType: "delivery",
    deliveryKind: "van_flat",
    vehicleClass: "van",
    presetBoxTruck: false,
    fullDay: false,
    twoAddresses: true,
    stairs: "none",
    requiredCrew: 1
  },
  {
    id: "cargo_van_small",
    group: "delivery",
    subgroup: "Cargo Van Delivery",
    name: "Cargo Van \u2014 Small Item Delivery",
    description: "One person + cargo van for a single small item.",
    pricing: { kind: "flat", weekday: R.cargoVanSmallItem, weekend: R.cargoVanSmallItem },
    serviceType: "delivery",
    deliveryKind: "cargo_van",
    vehicleClass: "van",
    presetBoxTruck: false,
    fullDay: false,
    twoAddresses: true,
    stairs: "none",
    requiredCrew: 1
  },
  junk("junk_eighth", "Junk Removal \u2014 1/8 Truck Load", 99, "A few bulky items (about a pickup-bed corner). Loading, hauling and disposal included."),
  junk("junk_quarter", "Junk Removal \u2014 1/4 Truck Load", 149, "About a pickup bed of junk. Loading, hauling and disposal included."),
  junk("junk_half", "Junk Removal \u2014 1/2 Truck Load", 249, "A room's worth of junk. Loading, hauling and disposal included."),
  junk("junk_three_quarter", "Junk Removal \u2014 3/4 Truck Load", 329, "A large room or small garage. Loading, hauling and disposal included."),
  junk("junk_full", "Junk Removal \u2014 Full Truck Load", 389, "A garage or full cleanout. Loading, hauling and disposal included."),
  junk("junk_sofa", "Couch / Sofa Removal", 99, "One couch or sofa hauled away and disposed of."),
  junk("junk_mattress", "Mattress Removal", 89, "One mattress or box spring hauled away and disposed of."),
  junk("junk_appliance", "Appliance Removal", 99, "One appliance hauled away and disposed of.")
];
var BOOKING_WINDOWS = [
  { key: "am", label: "8:00\u201310:00am", start: "08:00", end: "10:00", blockEnd: "12:00" },
  { key: "pm", label: "12:00\u20132:00pm", start: "12:00", end: "14:00", blockEnd: "17:00" }
];
var FULL_DAY_BLOCK_END = "17:00";
function phoenixIso(date, hhmm) {
  return (/* @__PURE__ */ new Date(`${date}T${hhmm}:00-07:00`)).toISOString();
}
function inServiceArea(zip) {
  return /^85[0-3]\d\d$/.test(zip.trim());
}
function priceBooking(service, date, flights) {
  const dayType = dayTypeOf(date);
  const rate = service.pricing[dayType];
  const lines = [];
  let summary;
  if (service.pricing.kind === "hourly") {
    const hours = service.pricing.minimumHours;
    lines.push({ name: `${service.name} \u2014 ${hours}-hour minimum ($${rate}/hr)`, amount: rate, quantity: hours });
    summary = `$${rate}/hr${dayType === "weekend" ? " (weekend rate)" : ""}, ${hours}-hour minimum. This is an estimate \u2014 you pay for the actual time.`;
  } else {
    lines.push({ name: service.name, amount: rate, quantity: 1 });
    summary = `$${rate} flat${dayType === "weekend" ? " (weekend price)" : ""}.`;
  }
  const clean = flights.map((f) => Math.max(0, Math.min(20, Math.floor(Number(f) || 0))));
  if (service.stairs === "extra_flight") {
    const extra = clean.reduce((sum, f) => sum + Math.max(0, f - 1), 0);
    if (extra > 0) lines.push({ name: "Additional flight of stairs", amount: R.extraFlightOfStairs, quantity: extra });
  } else if (service.stairs === "per_location") {
    const locations = clean.filter((f) => f > 0).length;
    if (locations > 0) lines.push({ name: "Piano \u2014 stairs / difficult access (per location)", amount: R.piano.stairsPerLocation, quantity: locations });
  }
  const total = lines.reduce((sum, line) => sum + line.amount * line.quantity, 0);
  if (service.pricing.kind === "flat" && lines.length > 1) summary = `$${total} total${dayType === "weekend" ? " (weekend price)" : ""}, stairs included.`;
  return { dayType, lines, total, hourly: service.pricing.kind === "hourly", summary };
}
function bookingDateLabel(date, long = false) {
  const [y, m, d] = date.split("-").map(Number);
  return new Intl.DateTimeFormat("en-US", {
    timeZone: "UTC",
    weekday: long ? "long" : "short",
    month: long ? "long" : "short",
    day: "numeric"
  }).format(new Date(Date.UTC(y, m - 1, d)));
}

// server/booking/availability.ts
var PHOENIX_OFFSET_MS = 7 * 60 * 60 * 1e3;
function phoenixParts(iso) {
  const ms = Date.parse(iso);
  if (Number.isNaN(ms)) return null;
  const local = new Date(ms - PHOENIX_OFFSET_MS);
  return {
    date: local.toISOString().slice(0, 10),
    minutes: local.getUTCHours() * 60 + local.getUTCMinutes()
  };
}
function halves(start, end, startDate) {
  const am = start.minutes < 12 * 60;
  const runsPastOne = end ? end.date > startDate || end.minutes > 13 * 60 : false;
  return { am, pm: !am || runsPastOne };
}
function occupancyFromHcp(row) {
  if (row.canceled || (row.status ?? "").toLowerCase().includes("cancel")) return null;
  if (!row.scheduled_start) return null;
  const resource = (row.resource ?? "").toLowerCase();
  const vehicleClass = resource === "truck" ? "box_truck" : resource === "van" ? "van" : null;
  if (!vehicleClass) return null;
  const start = phoenixParts(row.scheduled_start);
  if (!start) return null;
  const end = row.scheduled_end ? phoenixParts(row.scheduled_end) : null;
  return { date: start.date, vehicleClass, ...halves(start, end, start.date), ref: `hcp:${row.id ?? ""}`, createdAt: row.created_at };
}
var FULL_DAY_KINDS = /* @__PURE__ */ new Set(["two_br", "small_house", "hourly_4"]);
function jobVehicleClass(data, vehicleTypes) {
  const vehicleId = typeof data.vehicleId === "string" ? data.vehicleId : "";
  const type = vehicleTypes.get(vehicleId) ?? "";
  if (type === "box_truck") return "box_truck";
  if (type === "cargo_van" || type === "passenger_van") return "van";
  const name = String(data.vehicleName ?? "").toLowerCase();
  if (name.includes("box")) return "box_truck";
  if (name.includes("van") || name.startsWith("spr")) return "van";
  const serviceType = String(data.serviceType ?? "");
  if (serviceType === "moving" || serviceType === "labor_only" || serviceType === "specialty_moving") return "box_truck";
  if (serviceType === "delivery" || serviceType === "junk_removal" || serviceType === "assembly_handyman" || serviceType === "furniture_assembly") return "van";
  return null;
}
function occupancyFromJob(row, vehicleTypes) {
  const status = (row.status ?? "").toLowerCase();
  if (status === "canceled" || status === "cancelled") return null;
  const data = row.data ?? {};
  const startIso = row.scheduled_start ?? (typeof data.scheduledStart === "string" ? data.scheduledStart : null);
  if (!startIso) return null;
  const start = phoenixParts(startIso);
  if (!start) return null;
  const vehicleClass = jobVehicleClass(data, vehicleTypes);
  if (!vehicleClass) return null;
  const endIso = typeof data.scheduledEnd === "string" ? data.scheduledEnd : null;
  const end = endIso ? phoenixParts(endIso) : null;
  const fullDay = vehicleClass === "box_truck" && String(data.serviceType ?? "") === "moving" && FULL_DAY_KINDS.has(String(data.movingKind ?? ""));
  const h = fullDay ? { am: true, pm: true } : halves(start, end, start.date);
  return { date: start.date, vehicleClass, ...h, ref: `job:${row.id}`, createdAt: row.created_at };
}
function windowsForDay(service, date, occupied, rules2, ignoreRef) {
  const taken = { am: false, pm: false };
  for (const o of occupied) {
    if (o.date !== date || o.vehicleClass !== service.vehicleClass || ignoreRef && o.ref === ignoreRef) continue;
    if (o.am) taken.am = true;
    if (o.pm) taken.pm = true;
  }
  const windows = BOOKING_WINDOWS.filter((w) => !service.fullDay || w.key === "am").map((w) => {
    let open = service.fullDay ? !taken.am && !taken.pm : !taken[w.key];
    if (date < rules2.today || date === rules2.today && !rules2.allowSameDay) open = false;
    const startsAt = Date.parse(`${date}T${w.start}:00-07:00`);
    if (startsAt - rules2.nowMs < rules2.leadHours * 36e5) open = false;
    return { key: w.key, label: w.label, open };
  });
  return { date, windows };
}
function phoenixDate(ms, addDays = 0) {
  return new Date(ms - PHOENIX_OFFSET_MS + addDays * 864e5).toISOString().slice(0, 10);
}
function leadHoursFrom(value) {
  switch (value) {
    case "1 hour":
      return 1;
    case "4 hours":
      return 4;
    case "Next day":
      return 0;
    default:
      return 2;
  }
}

// server/payments/core.ts
import { z } from "zod";
var PaymentError = class extends Error {
  constructor(status, message) {
    super(message);
    this.status = status;
  }
};
var invoiceSchema = z.object({
  id: z.string().min(1),
  invoiceNumber: z.number().int().positive(),
  clientName: z.string().min(1),
  clientEmail: z.string().optional(),
  jobId: z.string(),
  status: z.enum(["draft", "sent", "partial", "overdue", "paid", "void"]),
  total: z.number().finite().nonnegative(),
  amountPaid: z.number().finite().nonnegative().optional(),
  discount: z.number().finite().nonnegative().optional(),
  taxRate: z.number().finite().min(0).max(100).optional(),
  dueDate: z.string(),
  createdAt: z.string(),
  amountDue: z.number().finite().nonnegative(),
  items: z.array(
    z.object({
      id: z.string(),
      name: z.string().min(1),
      quantity: z.number().finite().positive(),
      amount: z.number().finite().nonnegative(),
      taxable: z.boolean().optional()
    })
  ).min(1).max(200)
});

// server/payments/service.ts
import Stripe from "stripe";

// server/payments/received.ts
import { z as z2 } from "zod";
var money = z2.number().finite().min(0).max(999999.99).refine((value) => Math.abs(value * 100 - Math.round(value * 100)) < 1e-6);
var receivedPaymentInput = z2.object({
  requestId: z2.string().uuid(),
  invoiceId: z2.string().trim().min(1).max(200),
  method: z2.enum(["Zelle", "Cash", "Check", "Offline Credit Card", "ACH"]),
  amount: money.refine((value) => value > 0),
  expectedPaid: money,
  receivedDate: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine((value) => {
    const parsed = /* @__PURE__ */ new Date(value + "T12:00:00Z");
    return Number.isFinite(parsed.getTime()) && parsed.toISOString().slice(0, 10) === value;
  }),
  reference: z2.string().trim().min(1).max(200)
});

// server/payments/service.ts
import { createClient } from "@supabase/supabase-js";
function paymentConfig() {
  const key = process.env.STRIPE_SECRET_KEY;
  const url = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
  const dbKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  const origin = process.env.PAYMENT_BASE_URL || process.env.APP_BASE_URL;
  if (!key || !url || !dbKey || !origin)
    throw new PaymentError(
      503,
      "Card payments need server configuration. Contact the owner."
    );
  const live = /^(sk|rk)_live_/.test(key);
  if (!/^(sk|rk)_(test|live)_/.test(key) || live && process.env.STRIPE_LIVE_ENABLED !== "true")
    throw new PaymentError(
      503,
      "Live card payments are not enabled. Use the sandbox first."
    );
  const base = new URL(origin);
  if (base.protocol !== "https:" && !(base.protocol === "http:" && ["localhost", "127.0.0.1"].includes(base.hostname)))
    throw new PaymentError(503, "Payment return URL must use HTTPS.");
  if (base.username || base.password || base.search || base.hash || base.pathname !== "/")
    throw new PaymentError(503, "Payment return URL must be a site origin.");
  if (live && !process.env.STRIPE_ACCOUNT_ID)
    throw new PaymentError(
      503,
      "Verify the collecting Stripe account before going live."
    );
  return {
    stripe: new Stripe(key, { maxNetworkRetries: 2, timeout: 15e3 }),
    db: createClient(url, dbKey, { auth: { persistSession: false } }),
    live,
    origin: base.origin
  };
}
async function stripeAccount(stripe) {
  const account = await stripe.accounts.retrieve(null);
  if (process.env.STRIPE_ACCOUNT_ID && account.id !== process.env.STRIPE_ACCOUNT_ID)
    throw new PaymentError(
      503,
      "Stripe key belongs to a different collecting account."
    );
  if (/^(sk|rk)_live_/.test(process.env.STRIPE_SECRET_KEY || "") && !account.charges_enabled)
    throw new PaymentError(
      503,
      "The collecting Stripe account is not ready to accept payments."
    );
  return account.id;
}

// server/booking/deposit.ts
function cardDepositConfigured() {
  try {
    paymentConfig();
    return true;
  } catch {
    return false;
  }
}
async function depositCheckout(input) {
  const { stripe, db, live, origin } = paymentConfig();
  const accountId = await stripeAccount(stripe);
  const ref = encodeURIComponent(input.jobId);
  const previous = await rows(
    db.from("invoice_checkout_attempts").select("*").eq("invoice_id", input.invoiceId).eq("company_id", input.companyId).eq("livemode", live).in("state", ["creating", "open", "paid"]).order("created_at", { ascending: false }).limit(1)
  );
  const last = previous[0];
  if (last?.state === "paid") return { paid: true };
  if (last?.stripe_session_id) {
    const session2 = await stripe.checkout.sessions.retrieve(last.stripe_session_id);
    if (session2.payment_status === "paid") return { paid: true };
    if (session2.status === "open" && session2.url) return { url: session2.url };
    if (session2.status === "expired")
      await db.from("invoice_checkout_attempts").update({ state: "expired" }).eq("id", last.id).eq("state", "open");
  }
  const invoiceRow = await single(
    db.from("app_invoices").select("data").eq("id", input.invoiceId).eq("tenant_id", input.companyId).maybeSingle()
  );
  if (!invoiceRow) throw new PaymentError(404, "Booking invoice not found.");
  const data = invoiceRow.data;
  if ((data.amountPaid ?? 0) >= BOOKING_DEPOSIT) return { paid: true };
  const cents = Math.min(BOOKING_DEPOSIT * 100, Math.round((data.amountDue ?? 0) * 100));
  if (cents < 50) return { paid: true };
  const attempt = await single(
    db.rpc("reserve_invoice_checkout", {
      target_invoice: input.invoiceId,
      target_company: input.companyId,
      collecting_account: accountId,
      is_live: live,
      expected_data: invoiceRow.data,
      amount: cents
    })
  );
  const metadata = { attempt_id: attempt.id, invoice_id: input.invoiceId, company_id: input.companyId };
  const session = await stripe.checkout.sessions.create(
    {
      mode: "payment",
      allowed_payment_method_types: ["card"],
      client_reference_id: attempt.id,
      ...input.customerEmail ? { customer_email: input.customerEmail } : {},
      line_items: [
        {
          quantity: 1,
          price_data: {
            currency: "usd",
            unit_amount: attempt.amount_cents,
            product_data: {
              name: "Booking deposit \u2014 Progressive Transportation Services",
              description: `${input.serviceName}. Credited to your final bill; refundable if you cancel at least 24 hours ahead.`
            }
          }
        }
      ],
      metadata,
      payment_intent_data: { metadata },
      success_url: `${origin}/book?deposit=paid&ref=${ref}`,
      cancel_url: `${origin}/book?deposit=cancelled&ref=${ref}`,
      expires_at: Math.floor(Date.parse(attempt.expires_at) / 1e3)
    },
    { idempotencyKey: `booking-deposit:${attempt.id}` }
  );
  if (session.livemode !== live || !session.url)
    throw new PaymentError(503, "Stripe returned an unexpected checkout environment.");
  await single(db.rpc("attach_invoice_checkout", { attempt_id: attempt.id, session_id: session.id }));
  return { url: session.url };
}
async function single(query) {
  const { data, error } = await query;
  if (error) throw new PaymentError(503, error.message || "Payment records could not be saved.");
  return data;
}
async function rows(query) {
  return await single(query) ?? [];
}

// server/booking/handler.ts
var BRAND = "Progressive Transportation Services";
var PHONE_DISPLAY = "(480) 351-0291";
var DEFAULT_ALERT_TO = "abe@saguarotransport.com";
var BOX_TRUCK = { vehicleId: "box-01", vehicleName: "BOX-01 \xB7 2022 IHC MV607 26-ft Box Truck" };
var hits = /* @__PURE__ */ new Map();
function limited(bucket, ip, max, windowMs) {
  const key = `${bucket}:${ip || "unknown"}`;
  const now = Date.now();
  const entry = hits.get(key);
  if (!entry || entry.resetAt <= now) {
    hits.set(key, { count: 1, resetAt: now + windowMs });
    return false;
  }
  entry.count += 1;
  return entry.count > max;
}
async function loadContext() {
  const url = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  const slug = (process.env.SITE_COMPANY_SLUG ?? "").trim();
  if (!url || !key || !slug) return unavailable();
  const sb = createClient2(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
  const { data: company } = await sb.from("companies").select("id").eq("slug", slug).maybeSingle();
  if (!company) return unavailable();
  const { data: row } = await sb.from("app_settings").select("value").eq("tenant_id", company.id).eq("key", "online-booking").maybeSingle();
  const value = row?.value ?? {};
  const nextDay = value.leadTime === "Next day";
  const ids = Array.isArray(value.bookableServiceIds) ? value.bookableServiceIds.filter((id) => typeof id === "string") : null;
  return {
    sb,
    companyId: company.id,
    settings: {
      enabled: value.enabled !== false,
      allowSameDay: !nextDay && value.allowSameDay !== false,
      leadHours: leadHoursFrom(value.leadTime),
      bookableServiceIds: ids
    }
  };
}
function unavailable() {
  return { status: 503, body: { error: `Online booking isn't available right now. Please call ${PHONE_DISPLAY}.` } };
}
function bookable(ctx) {
  const ids = ctx.settings.bookableServiceIds;
  return BOOKING_SERVICES.filter((service) => !ids || ids.includes(service.id));
}
function rules(ctx, nowMs) {
  return { today: phoenixDate(nowMs), nowMs, allowSameDay: ctx.settings.allowSameDay, leadHours: ctx.settings.leadHours };
}
async function loadOccupancy(ctx, from, to) {
  const fromIso = phoenixIso(from, "00:00");
  const toIso = new Date(Date.parse(phoenixIso(to, "00:00")) + 864e5).toISOString();
  const [jobs, hcp, vehicles] = await Promise.all([
    ctx.sb.from("jobs").select("id, status, scheduled_start, created_at, data").eq("tenant_id", ctx.companyId).gte("scheduled_start", fromIso).lt("scheduled_start", toIso),
    ctx.sb.from("hcp_appointments").select("id, scheduled_start, scheduled_end, resource, status, canceled, created_at").eq("tenant_id", ctx.companyId).gte("scheduled_start", fromIso).lt("scheduled_start", toIso),
    ctx.sb.from("vehicles").select("id, vehicle_type")
  ]);
  if (jobs.error || hcp.error) throw new Error(jobs.error?.message ?? hcp.error?.message);
  const types = new Map(
    (vehicles.data ?? []).map((v) => [v.id, v.vehicle_type])
  );
  const out = [];
  for (const row of jobs.data ?? []) {
    const o = occupancyFromJob(row, types);
    if (o) out.push(o);
  }
  for (const row of hcp.data ?? []) {
    const o = occupancyFromHcp(row);
    if (o) out.push(o);
  }
  return out;
}
async function options(ctx) {
  return {
    status: 200,
    body: {
      enabled: ctx.settings.enabled,
      serviceIds: bookable(ctx).map((service) => service.id),
      deposit: BOOKING_DEPOSIT,
      cardDeposit: cardDepositConfigured(),
      refundHours: BOOKING_REFUND_HOURS,
      phone: PHONE_DISPLAY
    }
  };
}
async function availability(ctx, body) {
  const service = bookable(ctx).find((s) => s.id === body.serviceId);
  if (!service) return { status: 400, body: { error: "Choose a service first." } };
  const nowMs = Date.now();
  const r = rules(ctx, nowMs);
  const last = phoenixDate(nowMs, BOOKING_DAYS_AHEAD);
  const occupied = await loadOccupancy(ctx, r.today, last);
  const days = [];
  for (let i = 0; i <= BOOKING_DAYS_AHEAD; i++) {
    const date = phoenixDate(nowMs, i);
    const day = windowsForDay(service, date, occupied, r);
    days.push({ ...day, price: priceBooking(service, date, []).summary });
  }
  return { status: 200, body: { days } };
}
var str = (value, max) => typeof value === "string" ? value.trim().slice(0, max) : "";
function validateBooking(ctx, body) {
  const service = bookable(ctx).find((s) => s.id === body.serviceId);
  if (!service) return "Choose a service.";
  const date = str(body.date, 10);
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) return "Choose a date.";
  const window = BOOKING_WINDOWS.find((w) => w.key === body.window);
  if (!window || service.fullDay && window.key !== "am") return "Choose an arrival window.";
  const rawAddresses = Array.isArray(body.addresses) ? body.addresses.slice(0, 2) : [];
  const needed = service.twoAddresses ? 2 : 1;
  if (rawAddresses.length !== needed) return "Enter the address details.";
  const addresses = [];
  for (const raw of rawAddresses) {
    const a = raw && typeof raw === "object" ? raw : {};
    const address = {
      street: str(a.street, 160),
      unit: str(a.unit, 40),
      city: str(a.city, 80),
      zip: str(a.zip, 5),
      flights: Math.max(0, Math.min(20, Math.floor(Number(a.flights) || 0))),
      elevator: a.elevator === true,
      access: str(a.access, 300)
    };
    if (!address.street || !address.city || !/^\d{5}$/.test(address.zip)) return "Enter a full street address, city and ZIP.";
    addresses.push(address);
  }
  if (!inServiceArea(addresses[0].zip)) return `That address is outside our online-booking area. Please call ${PHONE_DISPLAY}.`;
  const firstName = str(body.firstName, 60);
  const lastName = str(body.lastName, 60);
  const phone = str(body.phone, 20);
  const email = str(body.email, 200);
  if (!firstName || !lastName) return "Enter your first and last name.";
  if (!/^[\d\s()+.-]{7,20}$/.test(phone) || phone.replace(/\D/g, "").length < 10) return "Enter a phone number we can reach you at.";
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return "Enter a valid email.";
  return {
    service,
    date,
    window,
    addresses,
    firstName,
    lastName,
    phone,
    email,
    notes: str(body.notes, 2e3),
    smsConsent: body.smsConsent === true,
    isBot: typeof body.company === "string" && body.company.trim().length > 0
  };
}
async function nextJobNumber(sb) {
  const { data } = await sb.from("jobs").select("job_number").order("created_at", { ascending: false }).limit(200);
  let max = 1e3;
  for (const row of data ?? []) {
    const n = Number(String(row.job_number ?? "").replace(/\D/g, ""));
    if (Number.isFinite(n) && n > max) max = n;
  }
  return `J-${max + 1}`;
}
var digits = (value) => (value ?? "").replace(/\D/g, "").slice(-10);
function oneLine(a) {
  return `${a.street}${a.unit ? ` ${a.unit}` : ""}, ${a.city}, AZ ${a.zip}`;
}
function stairsText(a) {
  const stairs = a.flights === 0 ? "Ground floor / no stairs" : `${a.flights} flight${a.flights === 1 ? "" : "s"} of stairs`;
  return `${stairs}${a.elevator ? " \xB7 elevator" : ""}`;
}
async function upsertClient(ctx, input, logText, nowIso) {
  const { data: rows2 } = await ctx.sb.from("clients").select("id, phone, email").eq("tenant_id", ctx.companyId).limit(1e4);
  const phone = digits(input.phone);
  const email = input.email.toLowerCase();
  const match = (rows2 ?? []).find((r) => phone && digits(r.phone) === phone) ?? (rows2 ?? []).find((r) => email && (r.email ?? "").toLowerCase() === email);
  const logEntry = { id: randomUUID(), createdAt: nowIso, author: "Online booking", text: logText };
  if (match) {
    const { data: full } = await ctx.sb.from("clients").select("data").eq("id", match.id).maybeSingle();
    const data2 = full?.data ?? {};
    const contactLog = Array.isArray(data2.contactLog) ? data2.contactLog : [];
    const { error: error2 } = await ctx.sb.from("clients").update({
      kind: "client",
      data: { ...data2, kind: "client", contactLog: [...contactLog, logEntry], updatedAt: nowIso }
    }).eq("id", match.id);
    if (error2) throw new Error(`client update: ${error2.message}`);
    return match.id;
  }
  const id = `website-booking-${randomUUID()}`;
  const first = input.addresses[0];
  const data = {
    id,
    kind: "client",
    firstName: input.firstName,
    lastName: input.lastName,
    phone: input.phone,
    email: input.email,
    address: `${first.street}${first.unit ? ` ${first.unit}` : ""}`,
    city: first.city,
    state: "AZ",
    zip: first.zip,
    smsSetting: input.smsConsent ? "receive" : "do_not_receive",
    leadSource: "Website",
    tags: ["Website", "Online booking"],
    contactLog: [logEntry],
    createdAt: nowIso,
    updatedAt: nowIso
  };
  const { error } = await ctx.sb.from("clients").insert({
    id,
    tenant_id: ctx.companyId,
    created_by: null,
    kind: "client",
    first_name: input.firstName,
    last_name: input.lastName,
    company: null,
    email: input.email,
    phone: input.phone,
    data
  });
  if (error) throw new Error(`client insert: ${error.message}`);
  return id;
}
async function createInvoice(ctx, input, jobId, price, nowIso) {
  const id = `inv-${randomUUID()}`;
  const notes = [
    `Online booking \u2014 a $${BOOKING_DEPOSIT} deposit holds the appointment and is credited to this invoice.`,
    `Deposit refundable if cancelled at least ${BOOKING_REFUND_HOURS} hours before the appointment.`,
    price.hourly ? "Hourly work: the final amount is set by actual time on site." : ""
  ].filter(Boolean).join(" ");
  for (let attempt = 0; attempt < 4; attempt++) {
    const { data: top } = await ctx.sb.from("app_invoices").select("invoice_number").order("invoice_number", { ascending: false }).limit(1);
    const number = Number(top?.[0]?.invoice_number ?? 1e3) + 1 + attempt;
    const invoice = {
      id,
      invoiceNumber: number,
      jobId,
      clientName: `${input.firstName} ${input.lastName}`,
      clientEmail: input.email,
      clientAddress: oneLine(input.addresses[0]),
      dueDate: input.date,
      createdAt: nowIso,
      total: price.total,
      amountDue: price.total,
      amountPaid: 0,
      // "sent" so the deposit card checkout can attach to it (drafts can't be collected).
      status: "sent",
      notes,
      items: price.lines.map((line) => ({ id: randomUUID(), name: line.name, quantity: line.quantity, amount: line.amount }))
    };
    const { error } = await ctx.sb.from("app_invoices").insert({ id, invoice_number: number, tenant_id: ctx.companyId, data: invoice });
    if (!error) return { id, number };
    if (error.code !== "23505") {
      console.error("[book] invoice insert failed:", error.message);
      return null;
    }
  }
  return null;
}
async function book(ctx, body) {
  const input = validateBooking(ctx, body);
  if (typeof input === "string") return { status: 400, body: { error: input } };
  if (input.isBot) return { status: 200, body: { ok: true, jobNumber: "J-0000" } };
  const { service, date, window } = input;
  const nowMs = Date.now();
  const r = rules(ctx, nowMs);
  const slotTaken = (occupied, ignoreRef) => !windowsForDay(service, date, occupied, r, ignoreRef).windows.find((w) => w.key === window.key)?.open;
  if (slotTaken(await loadOccupancy(ctx, date, date))) {
    return { status: 409, body: { error: "Sorry \u2014 that arrival window was just taken. Please pick another time.", code: "taken" } };
  }
  const nowIso = new Date(nowMs).toISOString();
  const price = priceBooking(service, date, input.addresses.map((a) => a.flights));
  const customerName = `${input.firstName} ${input.lastName}`;
  const scheduledStart = phoenixIso(date, window.start);
  const scheduledEnd = phoenixIso(date, service.fullDay ? FULL_DAY_BLOCK_END : window.blockEnd);
  const arrival = `${bookingDateLabel(date, true)}, ${window.label} (Arizona time)`;
  const clientId = await upsertClient(
    ctx,
    input,
    `Booked online: ${service.name} on ${arrival}. ${price.summary}${input.notes ? ` Notes: ${input.notes}` : ""}`,
    nowIso
  );
  const jobId = randomUUID();
  const jobNumber = await nextJobNumber(ctx.sb);
  const stopNames = service.twoAddresses ? ["Loading address", "Unloading address"] : ["Service address"];
  const stopTypes = service.twoAddresses ? ["pickup", "delivery"] : ["service"];
  const stops = input.addresses.map((a, index) => ({
    id: randomUUID(),
    jobId,
    stopOrder: index + 1,
    stopType: stopTypes[index],
    name: stopNames[index],
    address: `${a.street}${a.unit ? ` ${a.unit}` : ""}`,
    city: a.city,
    state: "AZ",
    zip: a.zip,
    contactName: customerName,
    contactPhone: input.phone,
    flights: a.flights,
    elevator: a.elevator,
    ...a.access ? { instructions: a.access } : {},
    ...index === 0 ? { arrivalWindowStart: scheduledStart, arrivalWindowEnd: phoenixIso(date, window.end) } : {},
    status: "pending",
    createdAt: nowIso,
    updatedAt: nowIso
  }));
  const data = {
    id: jobId,
    jobNumber,
    source: "website",
    createdAt: nowIso,
    updatedAt: nowIso,
    customerName,
    leadSource: "website",
    serviceType: service.serviceType,
    ...service.movingKind ? { movingKind: service.movingKind } : {},
    ...service.deliveryKind ? { deliveryKind: service.deliveryKind } : {},
    priority: "normal",
    requiredCrew: service.requiredCrew,
    crew: [],
    stops,
    items: [],
    dayType: price.dayType,
    quote: {
      tier: service.name,
      low: price.total,
      high: price.total,
      ...service.includedHours ? { includedHours: service.includedHours } : {},
      source: "booking"
    },
    paymentTerms: service.movingKind === "labor_only" ? "full_upfront" : "deposit",
    leadRef: { source: "website" },
    clientId,
    phone: input.phone,
    email: input.email,
    address: stops[0].address,
    city: stops[0].city,
    state: "AZ",
    zip: stops[0].zip,
    scheduledStart,
    scheduledEnd,
    ...service.presetBoxTruck ? BOX_TRUCK : {},
    status: "scheduled",
    paymentStatus: "unpaid",
    quotedAmount: price.total,
    notes: input.notes,
    internalNotes: [
      `Booked online ${new Date(nowMs).toLocaleString("en-US", { timeZone: "America/Phoenix" })}. Arrival ${window.label}.`,
      `Price shown to the customer: ${price.summary}`,
      `$${BOOKING_DEPOSIT} deposit: customer is sent to pay by card when card payments are on; if the invoice shows nothing paid, collect it and record it.`,
      input.smsConsent ? "Customer opted in to texts." : "Customer did NOT opt in to texts \u2014 call or email."
    ].join("\n"),
    booking: {
      serviceId: service.id,
      window: window.key,
      priceLines: price.lines,
      smsConsent: input.smsConsent,
      bookedAt: nowIso
    }
  };
  const { error: jobError } = await ctx.sb.from("jobs").insert({
    id: jobId,
    tenant_id: ctx.companyId,
    created_by: null,
    job_number: jobNumber,
    source: "website",
    customer_name: customerName,
    status: "scheduled",
    payment_status: "unpaid",
    scheduled_start: scheduledStart,
    quoted_amount: price.total,
    data
  });
  if (jobError) throw new Error(`job insert: ${jobError.message}`);
  const after = await loadOccupancy(ctx, date, date);
  const mine = after.find((o) => o.ref === `job:${jobId}`);
  const rival = after.find(
    (o) => o.ref !== `job:${jobId}` && o.date === date && o.vehicleClass === service.vehicleClass && (service.fullDay && (o.am || o.pm) || !service.fullDay && o[window.key]) && (!mine?.createdAt || !o.createdAt || o.createdAt < mine.createdAt || o.createdAt === mine.createdAt && o.ref < mine.ref)
  );
  if (rival) {
    await ctx.sb.from("jobs").delete().eq("id", jobId);
    return { status: 409, body: { error: "Sorry \u2014 that arrival window was just taken. Please pick another time.", code: "taken" } };
  }
  const invoice = await createInvoice(ctx, input, jobId, price, nowIso);
  if (invoice) {
    await ctx.sb.from("jobs").update({ data: { ...data, invoiceId: invoice.id } }).eq("id", jobId);
  }
  let checkoutUrl = null;
  if (invoice && cardDepositConfigured()) {
    try {
      const deposit = await depositCheckout({
        invoiceId: invoice.id,
        companyId: ctx.companyId,
        jobId,
        serviceName: service.name,
        customerEmail: input.email
      });
      if ("url" in deposit) checkoutUrl = deposit.url;
    } catch (error) {
      console.error("[book] deposit checkout failed:", error instanceof Error ? error.message : error);
    }
  }
  const summary = { input, price, arrival, jobId, jobNumber, invoiceNumber: invoice?.number ?? null, cardDeposit: Boolean(checkoutUrl) };
  await Promise.allSettled([sendOfficeEmail(summary), sendOfficeText(summary), sendCustomerEmail(summary)]);
  return {
    status: 200,
    body: { ok: true, ref: jobId, jobNumber, arrival, priceSummary: price.summary, total: price.total, deposit: BOOKING_DEPOSIT, checkoutUrl }
  };
}
async function depositLink(ctx, body) {
  const ref = str(body.ref, 64);
  if (!/^[0-9a-f-]{36}$/.test(ref)) return { status: 400, body: { error: "Booking not found." } };
  const { data: job } = await ctx.sb.from("jobs").select("id, status, data").eq("id", ref).eq("tenant_id", ctx.companyId).eq("source", "website").maybeSingle();
  const data = job?.data ?? {};
  if (!job || typeof data.invoiceId !== "string") return { status: 404, body: { error: "Booking not found." } };
  if (!cardDepositConfigured()) return { status: 503, body: { error: `Card payments are unavailable. Please call ${PHONE_DISPLAY}.` } };
  const result = await depositCheckout({
    invoiceId: data.invoiceId,
    companyId: ctx.companyId,
    jobId: job.id,
    serviceName: String(data.quote?.tier ?? "Your booking"),
    customerEmail: typeof data.email === "string" ? data.email : void 0
  });
  return { status: 200, body: "url" in result ? { checkoutUrl: result.url } : { paid: true } };
}
function escapeHtml(value) {
  return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
function fromAddress() {
  const configured = process.env.RESEND_FROM ?? "";
  const address = configured.match(/<([^>]+)>/)?.[1] ?? (configured.includes("@") ? configured.trim() : "onboarding@resend.dev");
  return `${BRAND} <${address}>`;
}
function appUrl(path) {
  const base = (process.env.APP_BASE_URL || "https://rejunk.vercel.app").replace(/\/$/, "");
  return `${base}${path}`;
}
function detailRows(s) {
  const { input, price } = s;
  const names = input.service.twoAddresses ? ["Loading", "Unloading"] : ["Address"];
  const rows2 = [
    ["Service", input.service.name],
    ["Arrival", s.arrival],
    ...input.addresses.map((a, i) => [
      names[i],
      `${oneLine(a)} \u2014 ${stairsText(a)}${a.access ? ` \u2014 ${a.access}` : ""}`
    ]),
    ["Price", price.summary],
    ...price.lines.map((l) => ["", `${l.name}${l.quantity > 1 ? ` \xD7 ${l.quantity}` : ""}: $${l.amount * l.quantity}`])
  ];
  if (input.notes) rows2.push(["Notes", input.notes]);
  return rows2.map(
    ([k, v]) => `<tr><td style="padding:6px 12px 6px 0;font-weight:600;vertical-align:top;white-space:nowrap">${escapeHtml(k)}</td><td style="padding:6px 0;color:#374151">${escapeHtml(v)}</td></tr>`
  ).join("");
}
function emailShell(title, inner) {
  return `<!doctype html><html><body style="margin:0;padding:0;background:#f4f6f3;font-family:system-ui,-apple-system,'Segoe UI',sans-serif;color:#1c1c1c">
<div style="max-width:560px;margin:0 auto;padding:24px 16px"><div style="background:#fff;border-radius:12px;border:1px solid #e2e6df;padding:28px 24px">
<h1 style="margin:0 0 12px;font-size:20px">${escapeHtml(title)}</h1>${inner}</div>
<p style="text-align:center;font-size:12px;color:#8a917f;margin:16px 0 0">${BRAND} \xB7 ${PHONE_DISPLAY}</p></div></body></html>`;
}
async function sendOfficeEmail(s) {
  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) return;
  const { input } = s;
  const html = emailShell(
    `New online booking \u2014 ${s.jobNumber}`,
    `<div style="background:#f0f4ec;border-radius:10px;padding:16px;margin:0 0 16px">
<p style="margin:0 0 6px;font-size:16px;font-weight:700">${escapeHtml(`${input.firstName} ${input.lastName}`)}</p>
<p style="margin:0;font-size:15px"><a href="tel:${escapeHtml(input.phone)}" style="color:#155e3f;font-weight:600">${escapeHtml(input.phone)}</a></p>
<p style="margin:6px 0 0;font-size:14px"><a href="mailto:${escapeHtml(input.email)}" style="color:#155e3f">${escapeHtml(input.email)}</a></p></div>
<table style="width:100%;border-collapse:collapse;font-size:14px">${detailRows(s)}</table>
<p style="margin:16px 0 0;font-size:14px;font-weight:600;color:#9a6a00">${s.cardDeposit ? `Customer was sent to pay the $${BOOKING_DEPOSIT} deposit by card \u2014 it shows on invoice #${s.invoiceNumber} once paid. If it doesn't, collect it.` : `$${BOOKING_DEPOSIT} deposit not collected yet${s.invoiceNumber ? ` \u2014 record it on invoice #${s.invoiceNumber}` : ""}.`}</p>
<p style="margin:8px 0 0;font-size:13px;color:#5b6357">${input.smsConsent ? "\u2713 Opted in to texts" : "Did not opt in to texts \u2014 call or email"} \xB7 Crew and vehicle: assign in Dispatch Center.</p>
<p style="margin:16px 0 0"><a href="${appUrl(`/jobs/${s.jobId}`)}" style="color:#155e3f;font-weight:700">Open the ticket \u2192</a></p>`
  );
  const { error } = await new Resend(apiKey).emails.send({
    from: fromAddress(),
    to: process.env.LEAD_TO || DEFAULT_ALERT_TO,
    subject: `New online booking \u2014 ${input.service.name} \u2014 ${s.arrival}`,
    html
  });
  if (error) console.error("[book] office email failed:", error.message);
}
async function sendCustomerEmail(s) {
  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) return;
  const { input } = s;
  const html = emailShell(
    `You're booked, ${input.firstName}!`,
    `<p style="margin:0 0 16px;font-size:15px;color:#374151">Thanks for booking with ${BRAND}. Here are your details:</p>
<table style="width:100%;border-collapse:collapse;font-size:14px">${detailRows(s)}</table>
<div style="background:#f0f4ec;border-radius:10px;padding:16px;margin:16px 0 0;font-size:14px;color:#1c1c1c">
<p style="margin:0 0 6px;font-weight:700">Your $${BOOKING_DEPOSIT} deposit</p>
<p style="margin:0">${s.cardDeposit ? `Your $${BOOKING_DEPOSIT} deposit holds your appointment. If you didn't finish paying it, call or text us and we'll help.` : `We'll contact you shortly to collect a $${BOOKING_DEPOSIT} deposit that holds your appointment.`} It comes off your final bill, and it's fully refundable if you cancel at least ${BOOKING_REFUND_HOURS} hours before your appointment.</p></div>
<p style="margin:16px 0 0;font-size:14px;color:#374151">Need to change something? Call or text us at <a href="tel:+14803510291" style="color:#155e3f;font-weight:600">${PHONE_DISPLAY}</a>. Booking ${escapeHtml(s.jobNumber)}.</p>`
  );
  const { error } = await new Resend(apiKey).emails.send({
    from: fromAddress(),
    to: input.email,
    subject: `Booking confirmed \u2014 ${s.arrival}`,
    html
  });
  if (error) console.error("[book] customer email failed:", error.message);
}
async function sendOfficeText(s) {
  const sid = process.env.TWILIO_ACCOUNT_SID;
  const token = process.env.TWILIO_AUTH_TOKEN;
  const from = process.env.TWILIO_PHONE_NUMBER;
  const to = (process.env.BOOKING_ALERT_PHONES ?? "").split(",").map((p) => p.trim()).filter(Boolean);
  if (!sid || !token || !from || !to.length) return;
  const { input } = s;
  const body = [
    `NEW ONLINE BOOKING ${s.jobNumber}`,
    `${input.firstName} ${input.lastName} ${input.phone}`,
    input.service.name,
    s.arrival,
    `${input.addresses[0].city}${input.addresses[1] ? ` \u2192 ${input.addresses[1].city}` : ""}`,
    s.price.summary,
    s.cardDeposit ? `Sent to pay $${BOOKING_DEPOSIT} deposit by card.` : `Collect $${BOOKING_DEPOSIT} deposit.`
  ].join("\n");
  await Promise.allSettled(
    to.map(async (phone) => {
      const res = await fetch(`https://api.twilio.com/2010-04-01/Accounts/${sid}/Messages.json`, {
        method: "POST",
        headers: {
          Authorization: `Basic ${Buffer.from(`${sid}:${token}`).toString("base64")}`,
          "Content-Type": "application/x-www-form-urlencoded"
        },
        body: new URLSearchParams({ To: phone, From: from, Body: body }).toString()
      });
      if (!res.ok) console.error("[book] office text failed:", res.status, await res.text());
    })
  );
}
async function handleBooking(rawBody, ip) {
  const body = rawBody && typeof rawBody === "object" ? rawBody : {};
  const action = body.action;
  if (action === "book") {
    if (limited("book", ip, 5, 15 * 6e4)) return { status: 429, body: { error: `Too many attempts. Please call ${PHONE_DISPLAY}.` } };
  } else if (limited("read", ip, 120, 5 * 6e4)) {
    return { status: 429, body: { error: "Too many requests. Please wait a minute." } };
  }
  const ctx = await loadContext();
  if ("status" in ctx) return ctx;
  if (action === "options") return options(ctx);
  if (!ctx.settings.enabled) return { status: 403, body: { error: `Online booking is off right now. Please call ${PHONE_DISPLAY}.` } };
  if (action === "availability") return availability(ctx, body);
  if (action === "book") return book(ctx, body);
  if (action === "deposit") return depositLink(ctx, body);
  return { status: 400, body: { error: "Unknown action." } };
}
function clientIp(req) {
  const forwarded = req.headers["x-forwarded-for"];
  const first = (Array.isArray(forwarded) ? forwarded[0] : forwarded)?.split(",")[0]?.trim();
  return first || req.socket?.remoteAddress || "";
}
async function handler(req, res) {
  res.setHeader("Cache-Control", "no-store");
  if (req.method !== "POST") return res.status(405).json({ error: "Use POST." });
  try {
    const result = await handleBooking(req.body, clientIp(req));
    return res.status(result.status).json(result.body);
  } catch (error) {
    console.error("[book] failed:", error instanceof Error ? error.message : error);
    return res.status(503).json({ error: `Something went wrong. Please call ${PHONE_DISPLAY}.` });
  }
}
export {
  clientIp,
  handler as default,
  handleBooking
};
