// Generated by scripts/security/build-mcp.mjs. Do not edit.

// mcp/handler.ts
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import { createClient } from "@supabase/supabase-js";

// mcp/pass.ts
import { createRemoteJWKSet, jwtVerify } from "jose";
function mcpConfig() {
  const supabaseUrl = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
  const anonKey = process.env.SUPABASE_ANON_KEY || process.env.VITE_SUPABASE_ANON_KEY;
  return supabaseUrl && anonKey ? { supabaseUrl: supabaseUrl.replace(/\/$/, ""), anonKey } : null;
}
var keys = null;
function signingKeys(supabaseUrl) {
  if (!keys || keys.url !== supabaseUrl) {
    keys = { url: supabaseUrl, set: createRemoteJWKSet(new URL(`${supabaseUrl}/auth/v1/.well-known/jwks.json`)) };
  }
  return keys.set;
}
async function verifyAiPass(header, config2) {
  const match = /^Bearer\s+(\S+)$/i.exec(header ?? "");
  if (!match) return null;
  let claims;
  try {
    ({ payload: claims } = await jwtVerify(match[1], signingKeys(config2.supabaseUrl), {
      issuer: `${config2.supabaseUrl}/auth/v1`,
      audience: "authenticated"
    }));
  } catch {
    return null;
  }
  const clientId = typeof claims.client_id === "string" ? claims.client_id : "";
  const sessionId = typeof claims.session_id === "string" ? claims.session_id : "";
  if (!claims.sub || !clientId || !sessionId || claims.role !== "authenticated") return null;
  return { token: match[1], userId: claims.sub, clientId, sessionId };
}

// mcp/handler.ts
var MCP_PATH = "/api/mcp";
var METADATA_PATH = "/.well-known/oauth-protected-resource";
function origin(req) {
  const proto = String(req.headers["x-forwarded-proto"] ?? "").split(",")[0] || "http";
  const host = String(req.headers["x-forwarded-host"] ?? req.headers.host ?? "localhost:3000").split(",")[0];
  return `${proto}://${host}`;
}
function send(res, status, body, headers = {}) {
  res.writeHead(status, { "Content-Type": "application/json", "Cache-Control": "no-store", ...headers });
  res.end(JSON.stringify(body));
}
function cors(res) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Authorization, Content-Type, Mcp-Protocol-Version, Mcp-Session-Id");
  res.setHeader("Access-Control-Expose-Headers", "WWW-Authenticate, Mcp-Session-Id");
}
function protectedResourceMetadata(req, config2) {
  return {
    resource: `${origin(req)}${MCP_PATH}`,
    authorization_servers: [`${config2.supabaseUrl}/auth/v1`],
    bearer_methods_supported: ["header"],
    resource_name: "Rejunk"
  };
}
async function readJson(req) {
  if (req.body !== void 0) return typeof req.body === "string" ? JSON.parse(req.body) : req.body;
  const chunks = [];
  let size = 0;
  for await (const chunk of req) {
    size += chunk.length;
    if (size > 1e6) throw new Error("Request too large");
    chunks.push(chunk);
  }
  return chunks.length ? JSON.parse(Buffer.concat(chunks).toString("utf8")) : void 0;
}
function buildServer(db) {
  const server = new McpServer({ name: "rejunk", version: "0.1.0" });
  server.registerTool(
    "rejunk_whoami",
    {
      title: "Who am I in Rejunk",
      description: "Shows which Rejunk company and role this connection reads as, and how many jobs that company has.",
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false }
    },
    async () => {
      const { data, error } = await db.rpc("mcp_whoami");
      if (error) {
        return { isError: true, content: [{ type: "text", text: "This connection isn't approved to read Rejunk data. Reconnect the app and approve it again." }] };
      }
      return { content: [{ type: "text", text: JSON.stringify(data) }] };
    }
  );
  return server;
}
async function handleMcpRequest(req, res) {
  cors(res);
  if (req.method === "OPTIONS") {
    res.writeHead(204);
    res.end();
    return;
  }
  const config2 = mcpConfig();
  if (!config2) {
    send(res, 503, { error: "MCP server is not configured" });
    return;
  }
  const url = new URL(req.url ?? "/", "http://x");
  if (url.pathname.startsWith(METADATA_PATH) || url.searchParams.has("resource-metadata")) {
    if (req.method !== "GET") {
      send(res, 405, { error: "Method not allowed" });
      return;
    }
    send(res, 200, protectedResourceMetadata(req, config2), { "Cache-Control": "public, max-age=300" });
    return;
  }
  const pass = await verifyAiPass(req.headers.authorization, config2);
  if (!pass) {
    const metadataUrl = `${origin(req)}${METADATA_PATH}`;
    const error = req.headers.authorization ? ', error="invalid_token"' : "";
    send(
      res,
      401,
      { error: "Sign in to Rejunk and approve this app first." },
      { "WWW-Authenticate": `Bearer resource_metadata="${metadataUrl}"${error}` }
    );
    return;
  }
  if (req.method !== "POST") {
    send(res, 405, { jsonrpc: "2.0", error: { code: -32e3, message: "Method not allowed." }, id: null }, { Allow: "POST" });
    return;
  }
  let body;
  try {
    body = await readJson(req);
  } catch {
    send(res, 400, { jsonrpc: "2.0", error: { code: -32700, message: "Parse error" }, id: null });
    return;
  }
  const db = createClient(config2.supabaseUrl, config2.anonKey, {
    auth: { persistSession: false, autoRefreshToken: false },
    global: { headers: { Authorization: `Bearer ${pass.token}` } }
  });
  const server = buildServer(db);
  const transport = new StreamableHTTPServerTransport({ sessionIdGenerator: void 0, enableJsonResponse: true });
  res.on("close", () => {
    void transport.close();
    void server.close();
  });
  await server.connect(transport);
  await transport.handleRequest(req, res, body);
}

// mcp/entry.ts
var config = { api: { bodyParser: false } };
var entry_default = (req, res) => handleMcpRequest(req, res);
export {
  config,
  entry_default as default
};
