// Generated by scripts/security/build-office-quote.mjs. Do not edit.

// server/officeQuote.ts
import { createClient } from "@supabase/supabase-js";

// client/src/utils/pricingCalculator.ts
var ROUND_TO_DOLLAR = 1;
var RECENT_VERIFICATION_DAYS = 180;
var BEDLOAD_YARDS = 3;
var DEFAULT_HEAVY_BEDLOAD_PRICING = {
  minimumEnvironmentalFee: 150,
  quarterBedload: 325,
  halfBedload: 495,
  threeQuarterBedload: 640,
  fullBedload: 775
};
function money(value) {
  if (!Number.isFinite(value)) {
    return 0;
  }
  return Math.round(value / ROUND_TO_DOLLAR) * ROUND_TO_DOLLAR;
}
function positive(value, fallback = 0) {
  return typeof value === "number" && Number.isFinite(value) && value > 0 ? value : fallback;
}
function isHeavyMaterial(rule) {
  return rule.handlingClass === "heavy_lowboy" || rule.requiresWeightOverride || rule.pricingMode === "weight_based" || rule.defaultDensityLbsPerYard >= 700 || ["clean_concrete", "clean_tile", "brick", "dirt", "rock"].includes(rule.materialCategory);
}
function bedloadTier(cubicYards, pricing) {
  const bedloadEquivalent = cubicYards / BEDLOAD_YARDS;
  if (cubicYards <= 0) {
    return {
      bedloadEquivalent,
      chargedBedloads: 0,
      tierLabel: "Minimum / environmental fee",
      baseBedloadPrice: pricing.minimumEnvironmentalFee
    };
  }
  if (cubicYards <= 0.75) {
    return { bedloadEquivalent, chargedBedloads: 0.25, tierLabel: "1/4 bedload", baseBedloadPrice: pricing.quarterBedload };
  }
  if (cubicYards <= 1.5) {
    return { bedloadEquivalent, chargedBedloads: 0.5, tierLabel: "1/2 bedload", baseBedloadPrice: pricing.halfBedload };
  }
  if (cubicYards <= 2.25) {
    return { bedloadEquivalent, chargedBedloads: 0.75, tierLabel: "3/4 bedload", baseBedloadPrice: pricing.threeQuarterBedload };
  }
  if (cubicYards <= BEDLOAD_YARDS) {
    return { bedloadEquivalent, chargedBedloads: 1, tierLabel: "Full bedload", baseBedloadPrice: pricing.fullBedload };
  }
  const chargedBedloads = Math.ceil(cubicYards / BEDLOAD_YARDS);
  return {
    bedloadEquivalent,
    chargedBedloads,
    tierLabel: `${chargedBedloads} full bedloads`,
    baseBedloadPrice: chargedBedloads * pricing.fullBedload
  };
}
function serviceForHeavyLoad(cubicYards, vehicle) {
  if (vehicle.vehicleType === "dump_trailer" && cubicYards >= 5 && cubicYards <= 10) return "dump trailer package";
  if (cubicYards > 10) return "manual review";
  const bedloads = Math.ceil(Math.max(cubicYards, 0.1) / BEDLOAD_YARDS);
  if (bedloads <= 1) return "1-trip heavy pickup";
  if (bedloads === 2) return "2-trip heavy pickup";
  return `${bedloads}-trip heavy pickup`;
}
function heavyBedloadDetails(input, cubicYards, estimatedTons) {
  if (input.materialRule.handlingClass !== "heavy_lowboy") return void 0;
  const pricing = {
    ...DEFAULT_HEAVY_BEDLOAD_PRICING,
    ...input.heavyBedloadPricing
  };
  const tier = bedloadTier(cubicYards, pricing);
  const includedTons = positive(input.materialRule.includedTons, 4) * Math.max(tier.chargedBedloads, 1);
  const extraTons = Math.max(0, estimatedTons - includedTons);
  const extraTonCharge = extraTons * positive(input.materialRule.extraTonRate, 95);
  return {
    bedloadYards: BEDLOAD_YARDS,
    bedloadEquivalent: tier.bedloadEquivalent,
    chargedBedloads: tier.chargedBedloads,
    tierLabel: tier.tierLabel,
    baseBedloadPrice: tier.baseBedloadPrice,
    includedTons,
    extraTons,
    extraTonCharge,
    recommendedService: serviceForHeavyLoad(cubicYards, input.vehicle),
    lowboyEquivalent: cubicYards >= 9.5 && cubicYards <= 10.5
  };
}
function facilityVerificationIsStale(lastVerifiedDate) {
  if (!lastVerifiedDate) {
    return true;
  }
  const verifiedAt = new Date(lastVerifiedDate).getTime();
  if (!Number.isFinite(verifiedAt)) {
    return true;
  }
  const ageDays = (Date.now() - verifiedAt) / (1e3 * 60 * 60 * 24);
  return ageDays > RECENT_VERIFICATION_DAYS;
}
function getDisposalCost(priceType, estimatedTons, rate, minimumCharge, itemCount) {
  switch (priceType) {
    case "per_ton":
      return Math.max(estimatedTons * rate, minimumCharge);
    case "flat_fee":
      return rate;
    case "per_item":
      return Math.max(itemCount * rate, minimumCharge);
    case "payout":
      return -Math.abs(itemCount > 0 ? itemCount * rate : estimatedTons * rate);
    case "free":
      return 0;
    default:
      return 0;
  }
}
function getPayloadStatus(estimatedWeightLbs, vehicle) {
  if (estimatedWeightLbs > vehicle.maxPayloadLbs) {
    return "over_limit";
  }
  if (estimatedWeightLbs >= vehicle.maxPayloadLbs * 0.85) {
    return "near_limit";
  }
  return "ok";
}
function buildWarnings(input, result) {
  const warnings = [];
  const heavyMaterial = isHeavyMaterial(input.materialRule);
  if (input.materialRule.pricingMode === "excluded") {
    warnings.push({
      code: "excluded_material",
      severity: "critical",
      message: "This material is marked as excluded. Do not accept it through normal junk removal pricing."
    });
  }
  if (result.payloadStatus === "over_limit") {
    warnings.push({
      code: "payload_exceeded",
      severity: "critical",
      message: `Estimated weight (${Math.round(result.estimatedWeightLbs)} lb) exceeds ${input.vehicle.vehicleName} payload (${input.vehicle.maxPayloadLbs} lb).`
    });
  } else if (result.payloadStatus === "near_limit") {
    warnings.push({
      code: "payload_near_limit",
      severity: "warning",
      message: `Estimated weight is within 15% of ${input.vehicle.vehicleName} payload. Verify weight before dispatch.`
    });
  }
  if (heavyMaterial) {
    warnings.push({
      code: "heavy_material",
      severity: input.manualWeightLbs ? "warning" : "critical",
      message: input.materialRule.handlingClass === "heavy_lowboy" ? "Dense material: volume may fit, but weight controls legality. Use bedload pricing and verify payload." : "Heavy material detected. Do not price by volume alone; use estimated weight, payload, labor, and facility disposal cost."
    });
  }
  if (input.materialRule.handlingClass === "heavy_lowboy" && input.vehicle.vehicleType === "box_truck") {
    warnings.push({
      code: "vehicle_mismatch",
      severity: "critical",
      message: "Box truck excluded: heavy loose debris should be handled with low-load equipment or split van/trailer trips."
    });
  }
  if (input.facility.rejectedMaterials.includes(input.materialRule.materialCategory)) {
    warnings.push({
      code: "facility_rejects_material",
      severity: "critical",
      message: `${input.facility.facilityName} is configured to reject ${input.materialRule.materialName}. Choose a compatible facility.`
    });
  }
  if (facilityVerificationIsStale(input.facility.lastVerifiedDate)) {
    warnings.push({
      code: "facility_not_verified_recently",
      severity: "warning",
      message: "Facility pricing has not been verified recently. Confirm rate, minimums, and accepted materials before quoting."
    });
  }
  if (result.cubicYards > input.vehicle.usableCubicYards) {
    warnings.push({
      code: "multiple_trips_likely",
      severity: "warning",
      message: `Load volume (${result.cubicYards.toFixed(1)} yd3) exceeds ${input.vehicle.vehicleName} usable capacity (${input.vehicle.usableCubicYards} yd3).`
    });
  }
  if (input.vehicle.vehicleType === "dump_trailer" && result.payloadStatus !== "ok") {
    warnings.push({
      code: "vehicle_mismatch",
      severity: "critical",
      message: "Dump trailer selected with a heavy load near or over payload. Confirm trailer payload and tow rating."
    });
  }
  if (input.materialRule.handlingClass === "heavy_lowboy" && result.cubicYards > 3 && input.vehicle.vehicleType !== "dump_trailer") {
    warnings.push({
      code: "multiple_trips_likely",
      severity: "warning",
      message: "Split load required for more than one heavy material bedload."
    });
  }
  if (input.materialRule.handlingClass === "heavy_lowboy" && result.cubicYards > 10 && input.vehicle.vehicleType !== "dump_trailer") {
    warnings.push({
      code: "vehicle_mismatch",
      severity: "critical",
      message: "Manual review recommended above 10 yd3 without a dump trailer or lowboy plan."
    });
  }
  if (heavyMaterial && result.selectedVolumeBenchmark && result.finalRecommendedQuote <= result.selectedVolumeBenchmark) {
    warnings.push({
      code: "margin_below_target",
      severity: "warning",
      message: "Heavy material quote is close to the volume benchmark. Recheck disposal and labor assumptions before presenting."
    });
  }
  return warnings;
}
function calculateEstimate(input) {
  const cubicYards = positive(input.cubicYards, input.vehicle.usableCubicYards * positive(input.loadFraction, 0));
  const estimatedWeightLbs = positive(input.manualWeightLbs, cubicYards * input.materialRule.defaultDensityLbsPerYard);
  const estimatedTons = estimatedWeightLbs / 2e3;
  const workers = positive(input.workers, 2);
  const estimatedHours = positive(input.estimatedHours, 2);
  const hourlyLaborCost = positive(input.hourlyLaborCost, 25);
  const roundTripMiles = positive(input.roundTripMiles, 0);
  const mpg = positive(input.mpg, input.vehicle.mpgLoaded || input.vehicle.mpgUnloaded || 12);
  const fuelPricePerGallon = positive(input.fuelPricePerGallon, 4);
  const targetMarginDecimal = Math.min(Math.max(positive(input.targetMarginDecimal, 0.6), 0), 0.95);
  const minimumProfitDollars = positive(input.minimumProfitDollars, 150);
  const itemCount = Math.max(0, Math.round(positive(input.itemCount, 0)));
  const disposalRate = positive(input.overrideDisposalRate, input.facility.defaultRate);
  const laborCost = workers * hourlyLaborCost * estimatedHours * input.materialRule.laborDifficultyMultiplier;
  const disposalBeforeDifficulty = getDisposalCost(
    input.facility.priceType,
    estimatedTons,
    disposalRate,
    input.facility.minimumCharge,
    itemCount
  );
  const disposalCost = disposalBeforeDifficulty * input.materialRule.disposalDifficultyMultiplier + input.facility.environmentalFee + input.facility.fuelSurcharge + input.facility.extraFees;
  const fuelCost = input.manualFuelCost ?? roundTripMiles / mpg * fuelPricePerGallon;
  const vehicleCost = typeof input.vehicle.hourlyVehicleCost === "number" ? estimatedHours * input.vehicle.hourlyVehicleCost : roundTripMiles * positive(input.vehicle.mileageCost, 0);
  const extraFeesTotal = (input.extraFees ?? []).reduce((total, fee) => total + positive(fee.amount, 0), 0);
  const heavyBedload = heavyBedloadDetails(input, cubicYards, estimatedTons);
  const baseCost = laborCost + disposalCost + fuelCost + vehicleCost + extraFeesTotal;
  const recommendedQuote = targetMarginDecimal >= 0.95 ? baseCost : baseCost / (1 - targetMarginDecimal);
  const minimumQuote = baseCost + minimumProfitDollars;
  const heavyMaterial = isHeavyMaterial(input.materialRule);
  const applicableBenchmark = heavyMaterial ? void 0 : input.volumeBenchmarkPrice;
  const heavyBedloadQuote = heavyBedload ? heavyBedload.baseBedloadPrice + heavyBedload.extraTonCharge : 0;
  const finalRecommendedQuote = Math.max(
    recommendedQuote,
    minimumQuote,
    positive(applicableBenchmark, 0),
    heavyBedloadQuote,
    positive(input.minimumAcceptablePrice, 0)
  );
  const grossProfitDollars = finalRecommendedQuote - baseCost;
  const grossMarginDecimal = finalRecommendedQuote > 0 ? grossProfitDollars / finalRecommendedQuote : 0;
  const payloadStatus = getPayloadStatus(estimatedWeightLbs, input.vehicle);
  const resultWithoutWarnings = {
    cubicYards,
    estimatedWeightLbs,
    estimatedTons,
    laborCost: money(laborCost),
    disposalCost: money(disposalCost),
    fuelCost: money(fuelCost),
    vehicleCost: money(vehicleCost),
    extraFeesTotal: money(extraFeesTotal),
    baseCost: money(baseCost),
    recommendedQuote: money(recommendedQuote),
    minimumQuote: money(minimumQuote),
    finalRecommendedQuote: money(finalRecommendedQuote),
    grossProfitDollars: money(grossProfitDollars),
    grossMarginDecimal,
    selectedVolumeBenchmark: applicableBenchmark,
    heavyBedload: heavyBedload ? {
      ...heavyBedload,
      baseBedloadPrice: money(heavyBedload.baseBedloadPrice),
      extraTonCharge: money(heavyBedload.extraTonCharge)
    } : void 0,
    payloadStatus
  };
  return {
    ...resultWithoutWarnings,
    warnings: buildWarnings(input, resultWithoutWarnings)
  };
}
function findVolumeBenchmark(benchmarks, loadFraction) {
  if (typeof loadFraction !== "number") {
    return void 0;
  }
  return benchmarks.slice().sort((a, b) => a.fraction - b.fraction).find((benchmark) => loadFraction <= benchmark.fraction);
}

// shared/pricingRows.ts
function deriveAcceptance(accepted, facilityType) {
  return {
    tires: accepted.includes("tires"),
    appliances: accepted.includes("appliances"),
    recycling: facilityType === "recycling_center" || accepted.includes("cardboard") || accepted.includes("metal"),
    hazardousWaste: accepted.includes("hazardous_excluded")
  };
}
function derivePricing(row) {
  const rateLabel = (() => {
    switch (row.price_type) {
      case "free":
        return "Free";
      case "per_ton":
        return `$${row.default_rate}/ton estimate`;
      case "per_item":
        return `$${row.default_rate}/item estimate`;
      case "flat_fee":
        return `$${row.default_rate} flat fee`;
      case "payout":
        return `Payout $${row.default_rate}`;
      default:
        return void 0;
    }
  })();
  return {
    msw: rateLabel,
    minimum: row.minimum_charge > 0 ? `$${row.minimum_charge} minimum estimate` : void 0
  };
}
function defaultHandlingClass(materialCategory) {
  if ([
    "clean_concrete",
    "dirt",
    "rock",
    "sod",
    "stone",
    "brick",
    "clean_tile",
    "asphalt",
    "pavers",
    "heavy_clean_debris"
  ].includes(materialCategory)) {
    return "heavy_lowboy";
  }
  if (materialCategory === "green_waste") return "green_waste";
  if (materialCategory === "mixed_c_and_d") return "mixed_demo";
  if (materialCategory === "appliances" || materialCategory === "metal")
    return "metal_appliance";
  return "standard_junk";
}
function facilityFromRow(row) {
  const facilityType = row.facility_type;
  return {
    id: row.id,
    facilityName: row.facility_name,
    facilityType,
    address: row.address ?? "",
    city: row.city ?? "",
    state: row.state ?? "",
    zip: row.zip ?? "",
    phone: row.phone ?? void 0,
    website: row.website ?? void 0,
    latitude: row.latitude ?? 0,
    longitude: row.longitude ?? 0,
    acceptedMaterials: row.accepted_materials,
    rejectedMaterials: row.rejected_materials,
    priceType: row.price_type,
    defaultRate: row.default_rate,
    minimumCharge: row.minimum_charge,
    environmentalFee: row.environmental_fee,
    fuelSurcharge: row.fuel_surcharge,
    extraFees: row.extra_fees,
    hours: row.hours,
    notes: row.notes ?? void 0,
    bestUseCase: row.best_use_case ?? void 0,
    pricingImpactLabel: row.pricing_impact_label ?? void 0,
    lastVerifiedDate: row.last_verified_date ?? void 0,
    isDefault: row.is_default,
    isActive: row.is_active,
    // Legacy display fields (consumed by Map/FacilityDetails). Reconstructed
    // from the canonical columns since they are not stored separately.
    name: row.facility_name,
    type: facilityType,
    lat: row.latitude ?? 0,
    lng: row.longitude ?? 0,
    description: row.best_use_case ?? row.notes ?? "",
    pricing: derivePricing(row),
    acceptance: deriveAcceptance(row.accepted_materials, row.facility_type)
  };
}
function vehicleFromRow(row) {
  const vehicleType = row.vehicle_type;
  const heavyMaterialSuitable = vehicleType === "dump_trailer" ? true : vehicleType === "cargo_van" ? "conditional" : false;
  const bedHeightClass = vehicleType === "dump_trailer" ? "low" : vehicleType === "box_truck" ? "high" : "medium";
  const allowedHandlingClasses = vehicleType === "box_truck" ? [
    "standard_junk",
    "green_waste",
    "mixed_demo",
    "metal_appliance"
  ] : [
    "standard_junk",
    "green_waste",
    "mixed_demo",
    "metal_appliance",
    "heavy_lowboy"
  ];
  return {
    id: row.id,
    vehicleName: row.vehicle_name,
    vehicleType,
    usableCubicYards: row.usable_cubic_yards,
    maxPayloadLbs: row.max_payload_lbs,
    emptyWeightLbs: row.empty_weight_lbs ?? void 0,
    gvwrLbs: row.gvwr_lbs ?? void 0,
    fuelType: row.fuel_type ?? "",
    mpgUnloaded: row.mpg_unloaded ?? 0,
    mpgLoaded: row.mpg_loaded ?? 0,
    hourlyVehicleCost: row.hourly_vehicle_cost ?? void 0,
    mileageCost: row.mileage_cost ?? void 0,
    hasLiftgate: row.has_liftgate,
    hasDumpCapability: row.has_dump_capability,
    requiresTowVehicle: row.requires_tow_vehicle,
    allowedHandlingClasses: [...allowedHandlingClasses],
    bedHeightClass,
    looseDebrisSuitable: vehicleType !== "box_truck",
    heavyMaterialSuitable,
    notes: row.notes ?? void 0,
    isDefault: row.is_default,
    isActive: row.is_active
  };
}
function materialFromRow(row) {
  const materialCategory = row.material_category;
  const handlingClass = defaultHandlingClass(materialCategory);
  const range = row.density_range_min != null && row.density_range_max != null ? [row.density_range_min, row.density_range_max] : void 0;
  return {
    id: row.id,
    materialName: row.material_name,
    materialCategory,
    defaultDensityLbsPerYard: row.default_density_lbs_per_yard,
    densityRangeLbsPerYard: range,
    pricingMode: row.pricing_mode,
    handlingClass,
    requiresWeightOverride: row.requires_weight_override,
    preferredFacilityTypes: row.preferred_facility_types,
    includedTons: handlingClass === "heavy_lowboy" ? materialCategory === "heavy_clean_debris" ? 3 : 4 : void 0,
    extraTonRate: handlingClass === "heavy_lowboy" ? 95 : void 0,
    warningText: row.warning_text ?? void 0,
    laborDifficultyMultiplier: row.labor_difficulty_multiplier,
    disposalDifficultyMultiplier: row.disposal_difficulty_multiplier,
    notes: row.notes ?? void 0,
    isActive: row.is_active
  };
}
function defaultsFromRow(row) {
  return {
    fuelPricePerGallon: row.fuel_price_per_gallon,
    workers: row.workers,
    hourlyLaborCost: row.hourly_labor_cost,
    estimatedHours: row.estimated_hours,
    targetMarginDecimal: row.target_margin_decimal,
    minimumProfitDollars: row.minimum_profit_dollars,
    defaultFacilityRatePerTon: row.default_facility_rate_per_ton
  };
}

// client/src/data/defaultPricing.ts
var defaultHeavyBedloadPricing = {
  minimumEnvironmentalFee: 150,
  quarterBedload: 325,
  halfBedload: 495,
  threeQuarterBedload: 640,
  fullBedload: 775
};
var defaultVolumePricingBenchmarks = [
  { id: "minimum", label: "Minimum", fraction: 0, price: 150 },
  { id: "one-eighth", label: "1/8 Load", fraction: 1 / 8, price: 295 },
  { id: "one-sixth", label: "1/6 Load", fraction: 1 / 6, price: 395 },
  { id: "one-quarter", label: "1/4 Load", fraction: 1 / 4, price: 495 },
  { id: "one-third", label: "1/3 Load", fraction: 1 / 3, price: 575 },
  { id: "three-eighths", label: "3/8 Load", fraction: 3 / 8, price: 655 },
  { id: "one-half", label: "1/2 Load", fraction: 1 / 2, price: 695 },
  { id: "five-eighths", label: "5/8 Load", fraction: 5 / 8, price: 745 },
  { id: "two-thirds", label: "2/3 Load", fraction: 2 / 3, price: 815 },
  { id: "three-quarters", label: "3/4 Load", fraction: 3 / 4, price: 865 },
  { id: "seven-eighths", label: "7/8 Load", fraction: 7 / 8, price: 995 },
  { id: "full", label: "Full Load", fraction: 1, price: 1195 }
];

// server/officeQuote.ts
function number(value, fallback, max) {
  if (value === void 0 || value === "") return fallback;
  if (typeof value !== "number" || !Number.isFinite(value) || value < 0 || value > max)
    throw new Error("Invalid quote input.");
  return value;
}
async function quoteForStaff(db, body) {
  if (typeof body.token !== "string" || body.token.length > 256)
    return { status: 401, body: { error: "Sign in required." } };
  const { data: session, error: sessionError } = await db.from("staff_sessions").select("staff_id,expires_at").eq("token", body.token).maybeSingle();
  if (sessionError || !session || new Date(session.expires_at).getTime() <= Date.now())
    return { status: 401, body: { error: "Sign in required." } };
  const { data: staff, error: staffError } = await db.from("staff").select("id,role,active").eq("id", session.staff_id).maybeSingle();
  if (staffError || !staff?.active || !["owner", "office"].includes(staff.role))
    return { status: 403, body: { error: "Office access required." } };
  if (["facilityId", "vehicleId", "materialId"].some(
    (key) => typeof body[key] !== "string" || !body[key].length || body[key].length > 200
  )) {
    return {
      status: 400,
      body: { error: "Select a material, vehicle, and facility." }
    };
  }
  const responses = await Promise.all([
    db.from("facilities").select("*").eq("id", body.facilityId).eq("is_active", true).maybeSingle(),
    db.from("vehicles").select("*").eq("id", body.vehicleId).eq("is_active", true).maybeSingle(),
    db.from("material_pricing_rules").select("*").eq("id", body.materialId).eq("is_active", true).maybeSingle(),
    db.from("pricing_defaults").select("*").eq("id", 1).maybeSingle(),
    db.from("volume_benchmarks").select("*")
  ]);
  if (responses.some((r) => r.error))
    return {
      status: 503,
      body: { error: "Quote settings could not be loaded." }
    };
  const [f, v, m, d, b] = responses.map((r) => r.data);
  if (!f || !v || !m || !d)
    return {
      status: 400,
      body: { error: "Select an active material, vehicle, and facility." }
    };
  try {
    const defaults = defaultsFromRow(d);
    const loadFraction = number(body.loadFraction, 1, 10);
    const result = calculateEstimate({
      materialRule: materialFromRow(m),
      vehicle: vehicleFromRow(v),
      facility: facilityFromRow(f),
      loadFraction,
      cubicYards: body.cubicYards === void 0 ? void 0 : number(body.cubicYards, 0, 1e3),
      manualWeightLbs: body.manualWeightLbs === void 0 ? void 0 : number(body.manualWeightLbs, 0, 2e5),
      workers: number(body.workers, defaults.workers, 50),
      estimatedHours: number(body.estimatedHours, defaults.estimatedHours, 200),
      roundTripMiles: number(body.roundTripMiles, 0, 5e3),
      hourlyLaborCost: defaults.hourlyLaborCost,
      fuelPricePerGallon: defaults.fuelPricePerGallon,
      targetMarginDecimal: defaults.targetMarginDecimal,
      minimumProfitDollars: defaults.minimumProfitDollars,
      volumeBenchmarkPrice: findVolumeBenchmark(b, loadFraction)?.price,
      heavyBedloadPricing: defaultHeavyBedloadPricing,
      extraFees: []
    });
    const { data: quoteId, error: quoteError } = await db.rpc(
      "store_office_quote",
      { staff_id: staff.id, quote_data: result }
    );
    if (quoteError || typeof quoteId !== "string")
      return {
        status: 503,
        body: { error: "Quote could not be saved securely." }
      };
    return {
      status: 200,
      body: {
        quote: {
          quoteId,
          cubicYards: result.cubicYards,
          estimatedWeightLbs: result.estimatedWeightLbs,
          estimatedTons: result.estimatedTons,
          finalRecommendedQuote: result.finalRecommendedQuote,
          payloadStatus: result.payloadStatus,
          warnings: result.warnings.filter(
            (w) => w.code !== "margin_below_target"
          ),
          heavyBedload: result.heavyBedload
        }
      }
    };
  } catch {
    return { status: 400, body: { error: "Invalid quote input." } };
  }
}
async function handleOfficeQuote(body) {
  const url = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key)
    return { status: 503, body: { error: "Quote service is not configured." } };
  return quoteForStaff(
    createClient(url, key, { auth: { persistSession: false } }),
    body && typeof body === "object" ? body : {}
  );
}
async function handler(req, res) {
  res.setHeader("Cache-Control", "no-store");
  if (req.method !== "POST")
    return res.status(405).json({ error: "Use POST." });
  try {
    const result = await handleOfficeQuote(req.body);
    return res.status(result.status).json(result.body);
  } catch {
    return res.status(503).json({ error: "Quote service unavailable." });
  }
}
export {
  handler as default,
  handleOfficeQuote,
  quoteForStaff
};
